// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QBD2.Data;

#nullable disable

namespace QBD2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220404110714_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QBD2.Entities.MasterPart", b =>
                {
                    b.Property<int>("MasterPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterPartId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductFamilyId")
                        .HasColumnType("int");

                    b.HasKey("MasterPartId");

                    b.HasIndex("ProductFamilyId");

                    b.ToTable("MasterParts");

                    b.HasData(
                        new
                        {
                            MasterPartId = 1,
                            Description = "Delta Zulu GA",
                            PartNumber = "800-00025-001.2",
                            ProductFamilyId = 1
                        },
                        new
                        {
                            MasterPartId = 2,
                            Description = "ASSY, PCB, ANR, LEFT",
                            PartNumber = "200-00062-000"
                        },
                        new
                        {
                            MasterPartId = 3,
                            Description = "Faceplate, Left",
                            PartNumber = "303-00059-100"
                        },
                        new
                        {
                            MasterPartId = 4,
                            Description = "ASSY, PCB, ANR, RIGHT",
                            PartNumber = "200-00048-000"
                        },
                        new
                        {
                            MasterPartId = 5,
                            Description = "Faceplate, Right",
                            PartNumber = "303-00060-100"
                        },
                        new
                        {
                            MasterPartId = 6,
                            Description = "PCBA, Control Box Lower",
                            PartNumber = "200-00060-000"
                        },
                        new
                        {
                            MasterPartId = 7,
                            Description = "CONTROL BOX UPPER BOARD",
                            PartNumber = "200-00043-000"
                        },
                        new
                        {
                            MasterPartId = 8,
                            Description = "ANR Mic - Grooved, Aluminum",
                            PartNumber = "120-00008-101"
                        },
                        new
                        {
                            MasterPartId = 9,
                            Description = "DRIVER",
                            PartNumber = "119-00002-100"
                        });
                });

            modelBuilder.Entity("QBD2.Entities.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"), 1L, 1);

                    b.Property<int>("MasterPartId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentPartId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartId");

                    b.HasIndex("MasterPartId");

                    b.HasIndex("ParentPartId");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            PartId = 1,
                            MasterPartId = 1,
                            SerialNumber = "808000406"
                        },
                        new
                        {
                            PartId = 2,
                            MasterPartId = 2,
                            ParentPartId = 1,
                            SerialNumber = "71534*000135"
                        },
                        new
                        {
                            PartId = 3,
                            MasterPartId = 3,
                            ParentPartId = 1,
                            SerialNumber = "L51210055"
                        },
                        new
                        {
                            PartId = 4,
                            MasterPartId = 4,
                            ParentPartId = 1,
                            SerialNumber = "71543*000080"
                        },
                        new
                        {
                            PartId = 5,
                            MasterPartId = 5,
                            ParentPartId = 1,
                            SerialNumber = "R50210586"
                        },
                        new
                        {
                            PartId = 6,
                            MasterPartId = 6,
                            ParentPartId = 1,
                            SerialNumber = "71528*000047"
                        },
                        new
                        {
                            PartId = 7,
                            MasterPartId = 7,
                            ParentPartId = 1,
                            SerialNumber = "54658*000908"
                        },
                        new
                        {
                            PartId = 8,
                            MasterPartId = 8,
                            ParentPartId = 1,
                            SerialNumber = "2976833306*20210731037*A209601*2021-12-09*2Y*1*S*++*2801-20211207142***1"
                        },
                        new
                        {
                            PartId = 9,
                            MasterPartId = 9,
                            ParentPartId = 1,
                            SerialNumber = "2972833301*2792-20210413013*A219101*2021-12-20*8"
                        },
                        new
                        {
                            PartId = 10,
                            MasterPartId = 8,
                            ParentPartId = 1,
                            SerialNumber = "2976833306*20210731037*A209601*2021-12-09*2Y*1*S*++*2801-20211207142***1"
                        },
                        new
                        {
                            PartId = 11,
                            MasterPartId = 9,
                            ParentPartId = 1,
                            SerialNumber = "2972833301*2792-20210413013*A219101*2021-12-20*8"
                        });
                });

            modelBuilder.Entity("QBD2.Entities.ProductFamily", b =>
                {
                    b.Property<int>("ProductFamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductFamilyId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductFamilyId");

                    b.ToTable("ProductFamilies");

                    b.HasData(
                        new
                        {
                            ProductFamilyId = 1,
                            Name = "Delta Zulu"
                        });
                });

            modelBuilder.Entity("QBD2.Entities.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StationId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            StationId = 1,
                            Name = "Final Inspection"
                        });
                });

            modelBuilder.Entity("QBD2.Entities.MasterPart", b =>
                {
                    b.HasOne("QBD2.Entities.ProductFamily", "ProductFamily")
                        .WithMany()
                        .HasForeignKey("ProductFamilyId");

                    b.Navigation("ProductFamily");
                });

            modelBuilder.Entity("QBD2.Entities.Part", b =>
                {
                    b.HasOne("QBD2.Entities.MasterPart", "MasterPart")
                        .WithMany()
                        .HasForeignKey("MasterPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QBD2.Entities.Part", "ParentPart")
                        .WithMany()
                        .HasForeignKey("ParentPartId");

                    b.Navigation("MasterPart");

                    b.Navigation("ParentPart");
                });
#pragma warning restore 612, 618
        }
    }
}
